service: restana-sls

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs12.x
  region: us-east-1
  deploymentBucket: 
    name: serverless-kyberneees-aws
    maxPreviousDeploymentArtifacts: 1
  httpApi:
    cors: true

functions:
  service:
    handler: lambda.handler
    events:
      - httpApi:
          method: '*'
          path: '*'
